name: Trakt
options:
  bundleIdPrefix: com.ivanmz
  deploymentTarget:
    iOS: "18.0"
    watchOS: "11.0"
  developmentLanguage: en
  xcodeVersion: "26.2"
  createIntermediateGroups: true
  generateEmptyDirectories: true

schemes:
  Oracle:
    build:
      targets:
        Oracle: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  OracleWatch:
    build:
      targets:
        OracleWatch: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  OracleWidgetExtension:
    build:
      targets:
        OracleWidgetExtension: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

settings:
  base:
    DEVELOPMENT_TEAM: BH4ZLEBC89
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_APPROACHABLE_CONCURRENCY: YES
    SWIFT_UPCOMING_FEATURE_MEMBER_IMPORT_VISIBILITY: YES

targets:
  Oracle:
    type: application
    platform: iOS
    sources:
      - path: Trakt
        excludes:
          - Config/Secrets.example.swift
      - path: Shared
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: Trakt/Trakt.entitlements
        PRODUCT_NAME: Oracle
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        SWIFT_DEFAULT_ACTOR_ISOLATION: MainActor
        STRING_CATALOG_GENERATE_SYMBOLS: YES
    dependencies:
      - target: OracleWidgetExtension
      - target: OracleWatch

  OracleWatch:
    type: application
    platform: watchOS
    sources:
      - path: OracleWatch
      - path: Shared
      - path: Trakt/Models
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ivanmz.Oracle.watchkitapp
        PRODUCT_NAME: OracleWatch
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_WKCompanionAppBundleIdentifier: com.ivanmz.Oracle
        INFOPLIST_KEY_WKRunsIndependentlyOfCompanionApp: YES
        SWIFT_DEFAULT_ACTOR_ISOLATION: MainActor
        STRING_CATALOG_GENERATE_SYMBOLS: YES

  OracleWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: TraktWidget
        excludes:
          - Info.plist
      - path: Shared
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: TraktWidgetExtension.entitlements
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_FILE: TraktWidget/Info.plist
        INFOPLIST_KEY_CFBundleDisplayName: OracleWidget
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        PRODUCT_BUNDLE_IDENTIFIER: com.ivanmz.Oracle.OracleWidget
        PRODUCT_NAME: OracleWidgetExtension
        STRING_CATALOG_GENERATE_SYMBOLS: YES
        SKIP_INSTALL: YES
    frameworks:
      - sdk: WidgetKit.framework
      - sdk: SwiftUI.framework
